/******************************************************************************/
/****         Generated by IBExpert 2007.12.08 19/03/2008 19:54:20         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

SET CLIENTLIB 'C:\Arquivos de programas\Firebird\Firebird_1_5\bin\fbclient.dll';

CREATE DATABASE 'E:\Faculdade\8 Periodo\Projeto Final II\bd\GELIC.FDB'
USER 'sysdba' PASSWORD 'masterkey'
PAGE_SIZE 8192
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/

CREATE DOMAIN LOGRADOURO AS
VARCHAR(10)
CHECK (value in ('praça','rua','avenida'));



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_ENDERECOS_ID;
SET GENERATOR GEN_ENDERECOS_ID TO 0;

CREATE GENERATOR GEN_LICITACOES_ID;
SET GENERATOR GEN_LICITACOES_ID TO 7;

CREATE GENERATOR GEN_MODALIDADES_ID;
SET GENERATOR GEN_MODALIDADES_ID TO 3;

CREATE GENERATOR GEN_PRODUTOS_ID;
SET GENERATOR GEN_PRODUTOS_ID TO 2;

CREATE GENERATOR GEN_SISTEMAS_ID;
SET GENERATOR GEN_SISTEMAS_ID TO 3;

CREATE GENERATOR GEN_TIPOSLICITACOES_ID;
SET GENERATOR GEN_TIPOSLICITACOES_ID TO 2;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE ENDERECOS (
    ID          INTEGER NOT NULL,
    LOGRADOURO  LOGRADOURO NOT NULL
);

CREATE TABLE LICITACOES (
    ID                    INTEGER NOT NULL,
    TIPOLICITACAO         INTEGER NOT NULL,
    NUMERO                VARCHAR(10) NOT NULL,
    ANO                   SMALLINT NOT NULL,
    MODALIDADE            INTEGER NOT NULL,
    SISTEMA               INTEGER NOT NULL,
    ORGAO                 VARCHAR(14) NOT NULL,
    NUMEROPROCESSO        VARCHAR(20),
    OBJETO                VARCHAR(50) NOT NULL,
    DATADOCUMENTACAO      TIMESTAMP NOT NULL,
    DATAPROPOSTA          TIMESTAMP NOT NULL,
    DATAREALIZACAO        TIMESTAMP NOT NULL,
    DIASVALIDADEPROPOSTA  INTEGER NOT NULL,
    DIASPRAZOENTREGA      INTEGER NOT NULL,
    DIASPRAZOPAGAMENTO    INTEGER NOT NULL,
    DIASVIGENCIA          INTEGER NOT NULL,
    ANOSPRAZOGARANTIA     INTEGER NOT NULL,
    PEDEAMOSTRA           CHAR(1) NOT NULL,
    TERMOSAMOSTRA         VARCHAR(50),
    PEDEGARANTIA          CHAR(1) NOT NULL,
    TERMOSGARANTIA        VARCHAR(50),
    PREVEMULTA            CHAR(1) NOT NULL,
    TERMOSMULTA           VARCHAR(50),
    CONTATO               VARCHAR(30),
    STATUS                INTEGER
);

CREATE TABLE MODALIDADES (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(25)
);

CREATE TABLE ORGAOS (
    CNPJ         VARCHAR(14) NOT NULL,
    RAZAOSOCIAL  VARCHAR(50) NOT NULL,
    APELIDO      VARCHAR(15) NOT NULL,
    IE           NUMERIC(15,0)
);

CREATE TABLE PAPEIS (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(25) NOT NULL
);

CREATE TABLE PRODUTOS (
    ID           INTEGER NOT NULL,
    CODIGO       VARCHAR(4) NOT NULL,
    DESCRICAO    VARCHAR(30),
    PRECOVENDA   FLOAT,
    PRECOCOMPRA  FLOAT
);

CREATE TABLE SISTEMAS (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(30) NOT NULL
);

CREATE TABLE TIPOSLICITACOES (
    ID     INTEGER NOT NULL,
    NOME   VARCHAR(25) NOT NULL,
    SIGLA  VARCHAR(2) NOT NULL
);

CREATE TABLE USUARIOS (
    LOGIN  VARCHAR(25) NOT NULL,
    SENHA  VARCHAR(40),
    PAPEL  INTEGER
);



/******************************************************************************/
/****                          Unique Constraints                          ****/
/******************************************************************************/

ALTER TABLE LICITACOES ADD CONSTRAINT UNQ1_LICITACOES UNIQUE (TIPOLICITACAO, NUMERO, ANO, ORGAO);
ALTER TABLE PAPEIS ADD CONSTRAINT UNQ1_PAPEIS UNIQUE (NOME);
ALTER TABLE TIPOSLICITACOES ADD CONSTRAINT UNQ1_TIPOSLICITACOES UNIQUE (NOME);
ALTER TABLE TIPOSLICITACOES ADD CONSTRAINT UNQ2_TIPOSLICITACOES UNIQUE (SIGLA);


/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE LICITACOES ADD CONSTRAINT PK_LICITACOES PRIMARY KEY (ID);
ALTER TABLE MODALIDADES ADD CONSTRAINT PK_MODALIDADES PRIMARY KEY (ID);
ALTER TABLE ORGAOS ADD CONSTRAINT PK_ORGAOS PRIMARY KEY (CNPJ);
ALTER TABLE PAPEIS ADD CONSTRAINT PK_PAPEIS PRIMARY KEY (ID);
ALTER TABLE PRODUTOS ADD PRIMARY KEY (ID);
ALTER TABLE SISTEMAS ADD CONSTRAINT PK_SISTEMAS PRIMARY KEY (ID);
ALTER TABLE TIPOSLICITACOES ADD CONSTRAINT PK_TIPOSLICITACOES PRIMARY KEY (ID);
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (LOGIN);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE LICITACOES ADD CONSTRAINT FK_LICITACOES_1 FOREIGN KEY (TIPOLICITACAO) REFERENCES TIPOSLICITACOES (ID);
ALTER TABLE LICITACOES ADD CONSTRAINT FK_LICITACOES_2 FOREIGN KEY (MODALIDADE) REFERENCES MODALIDADES (ID);
ALTER TABLE LICITACOES ADD CONSTRAINT FK_LICITACOES_3 FOREIGN KEY (SISTEMA) REFERENCES SISTEMAS (ID);
ALTER TABLE LICITACOES ADD CONSTRAINT FK_LICITACOES_4 FOREIGN KEY (ORGAO) REFERENCES ORGAOS (CNPJ);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_1 FOREIGN KEY (PAPEL) REFERENCES PAPEIS (ID) ON UPDATE CASCADE;


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;


/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: ENDERECOS_BI */
CREATE TRIGGER ENDERECOS_BI FOR ENDERECOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_enderecos_id,1);
end
^

/* Trigger: LICITACOES_BI */
CREATE TRIGGER LICITACOES_BI FOR LICITACOES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_LICITACOES_ID,1);
END
^

/* Trigger: MODALIDADES_BI */
CREATE TRIGGER MODALIDADES_BI FOR MODALIDADES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_MODALIDADES_ID,1);
END
^

/* Trigger: PRODUTOS_BI */
CREATE TRIGGER PRODUTOS_BI FOR PRODUTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_PRODUTOS_ID,1);
END
^

/* Trigger: SISTEMAS_BI */
CREATE TRIGGER SISTEMAS_BI FOR SISTEMAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_SISTEMAS_ID,1);
END
^

/* Trigger: TIPOSLICITACOES_BI */
CREATE TRIGGER TIPOSLICITACOES_BI FOR TIPOSLICITACOES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_tiposlicitacoes_id,1);
end
^

SET TERM ; ^



/******************************************************************************/
/****                             Descriptions                             ****/
/******************************************************************************/

DESCRIBE TABLE LICITACOES
'Cadastro de licitações.';

DESCRIBE TABLE MODALIDADES
'Cadastro de modalidades.';

DESCRIBE TABLE ORGAOS
'Cadastro de órgãos públicos.';

DESCRIBE TABLE PAPEIS
'Cadastro de papéis.';

DESCRIBE TABLE PRODUTOS
'Cadastro de produtos.';

DESCRIBE TABLE SISTEMAS
'Cadastro de sistemas de licitação.';

DESCRIBE TABLE TIPOSLICITACOES
'Cadastro de tipos de licitações.';

DESCRIBE TABLE USUARIOS
'Cadastro de usuários.';



/* Fields descriptions */

DESCRIBE FIELD NUMERO TABLE LICITACOES
'Número da licitação.';

DESCRIBE FIELD MODALIDADE TABLE LICITACOES
'Modalidade da licitação.';

DESCRIBE FIELD SISTEMA TABLE LICITACOES
'Sistema da licitação.';

DESCRIBE FIELD NUMEROPROCESSO TABLE LICITACOES
'Numero do processo licitatório.';

DESCRIBE FIELD OBJETO TABLE LICITACOES
'Material que o órgão deseja comprar.';

DESCRIBE FIELD DATADOCUMENTACAO TABLE LICITACOES
'Data de apresentação da documentação.';

DESCRIBE FIELD DATAPROPOSTA TABLE LICITACOES
'Data de apresentação da proposta.';

DESCRIBE FIELD DATAREALIZACAO TABLE LICITACOES
'Data de realização da sessão da licitação.';

DESCRIBE FIELD DIASVALIDADEPROPOSTA TABLE LICITACOES
'Prazo de validade da proposta. Contado em dias.';

DESCRIBE FIELD DIASPRAZOENTREGA TABLE LICITACOES
'Prazo de entrega do material a ser fornecido. Contado em dias.';

DESCRIBE FIELD DIASPRAZOPAGAMENTO TABLE LICITACOES
'Prazo de pagamento das faturas pelo órgão público. Contado em dias.';

DESCRIBE FIELD DIASVIGENCIA TABLE LICITACOES
'Prazo de vigência do contrato. Contado em dias.';

DESCRIBE FIELD ANOSPRAZOGARANTIA TABLE LICITACOES
'Prazo de garantia dos objetos a serem fornecidos. Contado em anos.';

DESCRIBE FIELD PEDEAMOSTRA TABLE LICITACOES
'Campo de controle para saber se a licitação pede amostra.';

DESCRIBE FIELD TERMOSAMOSTRA TABLE LICITACOES
'Termos para apresentação de amostra.';

DESCRIBE FIELD PEDEGARANTIA TABLE LICITACOES
'Campo de controle para saber se a licitação pede garantia de proposta.';

DESCRIBE FIELD TERMOSGARANTIA TABLE LICITACOES
'Termos da garantia de proposta.';

DESCRIBE FIELD PREVEMULTA TABLE LICITACOES
'Campo de controle para informar se a licitação prevê multa por atraso na entrega.';

DESCRIBE FIELD TERMOSMULTA TABLE LICITACOES
'Termos da multa por atraso.';

DESCRIBE FIELD CONTATO TABLE LICITACOES
'Nome do principal responsável pela licitação.';

DESCRIBE FIELD STATUS TABLE LICITACOES
'Estado da licitação.';

DESCRIBE FIELD NOME TABLE MODALIDADES
'Nome da modalidade de licitação.';

DESCRIBE FIELD CNPJ TABLE ORGAOS
'CNPJ do órgão público.';

DESCRIBE FIELD RAZAOSOCIAL TABLE ORGAOS
'Razão social do órgão público.';

DESCRIBE FIELD APELIDO TABLE ORGAOS
'Apelido do órgão público.';

DESCRIBE FIELD IE TABLE ORGAOS
'Inscrição Estadual do órgão público, se houver.';

DESCRIBE FIELD ID TABLE PAPEIS
'Número de identificação do papel.';

DESCRIBE FIELD NOME TABLE PAPEIS
'Nome do papel.';

DESCRIBE FIELD ID TABLE PRODUTOS
'Numero de Identificação do produto gerado automaticamente.';

DESCRIBE FIELD CODIGO TABLE PRODUTOS
'     Código do produto. (ex: P1, M1, AB1)';

DESCRIBE FIELD DESCRICAO TABLE PRODUTOS
'Descrição completa do produto. (ex: Poltrona espaldar alto)';

DESCRIBE FIELD PRECOVENDA TABLE PRODUTOS
'Preço de venda do produto ao órgão publico.';

DESCRIBE FIELD PRECOCOMPRA TABLE PRODUTOS
'Preço de comprado do produto a ser pago ao fornecedor.';

DESCRIBE FIELD ID TABLE SISTEMAS
'Numero de identificação do sistema de licitação.';

DESCRIBE FIELD NOME TABLE SISTEMAS
'Nome do sistema de licitação.';

DESCRIBE FIELD ID TABLE TIPOSLICITACOES
'Numero de Identificação do tipo de licitação gerado automaticamente.';

DESCRIBE FIELD NOME TABLE TIPOSLICITACOES
'Nome do tipo de licitação.';

DESCRIBE FIELD SIGLA TABLE TIPOSLICITACOES
'Abreviação do nome do tipo de licitação.';

DESCRIBE FIELD LOGIN TABLE USUARIOS
'Login do usuário.';

DESCRIBE FIELD SENHA TABLE USUARIOS
'Senha do usuário.';

DESCRIBE FIELD PAPEL TABLE USUARIOS
'Papel do usuário no sistema.';

