/******************************************************************************/
/****         Generated by IBExpert 2007.12.08 06/03/2008 17:18:08         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

SET CLIENTLIB 'C:\Arquivos de programas\Firebird\Firebird_2_0\bin\fbclient.dll';

CREATE DATABASE 'E:\Adriano\Estácio\ProFin2\bd\GELIC.FDB'
USER 'sisgelic' PASSWORD 'gelic'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_TIPOSLICITACOES_ID;
SET GENERATOR GEN_TIPOSLICITACOES_ID TO 1;

/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE PAPEIS (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(25)
);

CREATE TABLE USUARIOS (
    LOGIN  VARCHAR(25) NOT NULL,
    SENHA  VARCHAR(40),
    PAPEL  INTEGER
);

CREATE TABLE MODALIDADES (
    SIGLA  VARCHAR(3) NOT NULL,
    NOME   VARCHAR(25)
);

CREATE TABLE LICITACOES (
    NUMERO      VARCHAR(10) NOT NULL,
    MODALIDADE  VARCHAR(3)
);

CREATE TABLE TIPOSLICITACOES (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(25) NOT NULL
);


INSERT INTO PAPEIS (ID, NOME) VALUES (1, 'Administrador');
INSERT INTO PAPEIS (ID, NOME) VALUES (2, 'Comercial');
INSERT INTO PAPEIS (ID, NOME) VALUES (3, 'Financeiro');
INSERT INTO PAPEIS (ID, NOME) VALUES (4, 'Analista');
INSERT INTO PAPEIS (ID, NOME) VALUES (5, 'GerenteComercial');

COMMIT WORK;

INSERT INTO USUARIOS (LOGIN, SENHA, PAPEL) VALUES ('admin', null, 1);
INSERT INTO USUARIOS (LOGIN, SENHA, PAPEL) VALUES ('com', null, 2);
INSERT INTO USUARIOS (LOGIN, SENHA, PAPEL) VALUES ('fin', null, 3);
INSERT INTO USUARIOS (LOGIN, SENHA, PAPEL) VALUES ('ana', null, 4);
INSERT INTO USUARIOS (LOGIN, SENHA, PAPEL) VALUES ('ger', null, 5);
COMMIT WORK;


/******************************************************************************/
/****                          Unique Constraints                          ****/
/******************************************************************************/

ALTER TABLE PAPEIS ADD CONSTRAINT UNQ1_PAPEIS UNIQUE (NOME);
ALTER TABLE TIPOSLICITACOES ADD CONSTRAINT UNQ1_TIPOSLICITACOES UNIQUE (NOME);


/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE LICITACOES ADD CONSTRAINT PK_LICITACOES PRIMARY KEY (NUMERO);
ALTER TABLE MODALIDADES ADD CONSTRAINT PK_MODALIDADES PRIMARY KEY (SIGLA);
ALTER TABLE PAPEIS ADD CONSTRAINT PK_PAPEIS PRIMARY KEY (ID);
ALTER TABLE TIPOSLICITACOES ADD CONSTRAINT PK_TIPOSLICITACOES PRIMARY KEY (ID);
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (LOGIN);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE LICITACOES ADD CONSTRAINT FK_LICITACOES_1 FOREIGN KEY (MODALIDADE) REFERENCES MODALIDADES (SIGLA) ON UPDATE CASCADE;
ALTER TABLE LICITACOES ADD CONSTRAINT FK_LICITACOES_2 FOREIGN KEY (TIPO) REFERENCES TIPOSLICITACOES (ID) ON UPDATE CASCADE;
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_1 FOREIGN KEY (PAPEL) REFERENCES PAPEIS (ID) ON UPDATE CASCADE;

/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;

/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: TIPOSLICITACOES_BI */
CREATE TRIGGER TIPOSLICITACOES_BI FOR TIPOSLICITACOES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_tiposlicitacoes_id,1);
end
^

SET TERM ; ^

