/******************************************************************************/
/****         Generated by IBExpert 2007.12.08 06/03/2008 17:18:08         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

SET CLIENTLIB 'C:\Arquivos de programas\Firebird\Firebird_1_5\bin\fbclient.dll';

CREATE DATABASE 'E:\Faculdade\8 Periodo\Projeto Final II\bd\GELIC.FDB'
USER 'sisgelic' PASSWORD 'gelic'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE PAPEIS (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(25)
);

CREATE TABLE USUARIOS (
    LOGIN  VARCHAR(25) NOT NULL,
    SENHA  VARCHAR(40),
    PAPEL  INTEGER
);

INSERT INTO PAPEIS (ID, NOME) VALUES (1, 'Administrador');
INSERT INTO PAPEIS (ID, NOME) VALUES (2, 'Comercial');
INSERT INTO PAPEIS (ID, NOME) VALUES (3, 'Financeiro');
INSERT INTO PAPEIS (ID, NOME) VALUES (4, 'Analista');
INSERT INTO PAPEIS (ID, NOME) VALUES (5, 'GerenteComercial');

COMMIT WORK;

INSERT INTO USUARIOS (LOGIN, SENHA, PAPEL) VALUES ('pgx', 'aa4d8b357cc476268aa06d0b833754d326912aed', 1);
INSERT INTO USUARIOS (LOGIN, SENHA, PAPEL) VALUES ('teste', 'da39a3ee5e6b4b0d3255bfef95601890afd80709', 2);
INSERT INTO USUARIOS (LOGIN, SENHA, PAPEL) VALUES ('novo', 'da39a3ee5e6b4b0d3255bfef95601890afd80709', 3);

COMMIT WORK;



/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE PAPEIS ADD CONSTRAINT PK_PAPEIS PRIMARY KEY (ID);
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (LOGIN);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_1 FOREIGN KEY (PAPEL) REFERENCES PAPEIS (ID) ON UPDATE CASCADE;
